# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='record.proto',
  package='codewithgpu',
  syntax='proto3',
  serialized_options=_b('\370\001\001'),
  serialized_pb=_b('\n\x0crecord.proto\x12\x0b\x63odewithgpu\"\xdc\x01\n\x07\x46\x65\x61ture\x12\x0b\n\x01s\x18\x01 \x01(\x0cH\x00\x12\x0b\n\x01\x66\x18\x02 \x01(\x02H\x00\x12\x0b\n\x01i\x18\x03 \x01(\x03H\x00\x12\x30\n\x0c\x66\x65\x61ture_list\x18\x04 \x01(\x0b\x32\x18.codewithgpu.FeatureListH\x00\x12.\n\x0b\x66\x65\x61ture_map\x18\x05 \x01(\x0b\x32\x17.codewithgpu.FeatureMapH\x00\"@\n\x0b\x46\x65\x61tureType\x12\r\n\tUNDEFINED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\x0b\n\x07\x46LOAT32\x10\x02\x12\t\n\x05INT64\x10\x03\x42\x06\n\x04kind\"6\n\x0b\x46\x65\x61tureList\x12\'\n\tcontainer\x18\x01 \x03(\x0b\x32\x14.codewithgpu.Feature\"\x8f\x01\n\nFeatureMap\x12\x39\n\tcontainer\x18\x01 \x03(\x0b\x32&.codewithgpu.FeatureMap.ContainerEntry\x1a\x46\n\x0e\x43ontainerEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.codewithgpu.Feature:\x02\x38\x01\x42\x03\xf8\x01\x01\x62\x06proto3')
)



_FEATURE_FEATURETYPE = _descriptor.EnumDescriptor(
  name='FeatureType',
  full_name='codewithgpu.Feature.FeatureType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT32', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INT64', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=178,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_FEATURE_FEATURETYPE)


_FEATURE = _descriptor.Descriptor(
  name='Feature',
  full_name='codewithgpu.Feature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='codewithgpu.Feature.s', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='f', full_name='codewithgpu.Feature.f', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='codewithgpu.Feature.i', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_list', full_name='codewithgpu.Feature.feature_list', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_map', full_name='codewithgpu.Feature.feature_map', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATURE_FEATURETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='codewithgpu.Feature.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=30,
  serialized_end=250,
)


_FEATURELIST = _descriptor.Descriptor(
  name='FeatureList',
  full_name='codewithgpu.FeatureList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='codewithgpu.FeatureList.container', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=306,
)


_FEATUREMAP_CONTAINERENTRY = _descriptor.Descriptor(
  name='ContainerEntry',
  full_name='codewithgpu.FeatureMap.ContainerEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='codewithgpu.FeatureMap.ContainerEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='codewithgpu.FeatureMap.ContainerEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=452,
)

_FEATUREMAP = _descriptor.Descriptor(
  name='FeatureMap',
  full_name='codewithgpu.FeatureMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container', full_name='codewithgpu.FeatureMap.container', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FEATUREMAP_CONTAINERENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=452,
)

_FEATURE.fields_by_name['feature_list'].message_type = _FEATURELIST
_FEATURE.fields_by_name['feature_map'].message_type = _FEATUREMAP
_FEATURE_FEATURETYPE.containing_type = _FEATURE
_FEATURE.oneofs_by_name['kind'].fields.append(
  _FEATURE.fields_by_name['s'])
_FEATURE.fields_by_name['s'].containing_oneof = _FEATURE.oneofs_by_name['kind']
_FEATURE.oneofs_by_name['kind'].fields.append(
  _FEATURE.fields_by_name['f'])
_FEATURE.fields_by_name['f'].containing_oneof = _FEATURE.oneofs_by_name['kind']
_FEATURE.oneofs_by_name['kind'].fields.append(
  _FEATURE.fields_by_name['i'])
_FEATURE.fields_by_name['i'].containing_oneof = _FEATURE.oneofs_by_name['kind']
_FEATURE.oneofs_by_name['kind'].fields.append(
  _FEATURE.fields_by_name['feature_list'])
_FEATURE.fields_by_name['feature_list'].containing_oneof = _FEATURE.oneofs_by_name['kind']
_FEATURE.oneofs_by_name['kind'].fields.append(
  _FEATURE.fields_by_name['feature_map'])
_FEATURE.fields_by_name['feature_map'].containing_oneof = _FEATURE.oneofs_by_name['kind']
_FEATURELIST.fields_by_name['container'].message_type = _FEATURE
_FEATUREMAP_CONTAINERENTRY.fields_by_name['value'].message_type = _FEATURE
_FEATUREMAP_CONTAINERENTRY.containing_type = _FEATUREMAP
_FEATUREMAP.fields_by_name['container'].message_type = _FEATUREMAP_CONTAINERENTRY
DESCRIPTOR.message_types_by_name['Feature'] = _FEATURE
DESCRIPTOR.message_types_by_name['FeatureList'] = _FEATURELIST
DESCRIPTOR.message_types_by_name['FeatureMap'] = _FEATUREMAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Feature = _reflection.GeneratedProtocolMessageType('Feature', (_message.Message,), {
  'DESCRIPTOR' : _FEATURE,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:codewithgpu.Feature)
  })
_sym_db.RegisterMessage(Feature)

FeatureList = _reflection.GeneratedProtocolMessageType('FeatureList', (_message.Message,), {
  'DESCRIPTOR' : _FEATURELIST,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:codewithgpu.FeatureList)
  })
_sym_db.RegisterMessage(FeatureList)

FeatureMap = _reflection.GeneratedProtocolMessageType('FeatureMap', (_message.Message,), {

  'ContainerEntry' : _reflection.GeneratedProtocolMessageType('ContainerEntry', (_message.Message,), {
    'DESCRIPTOR' : _FEATUREMAP_CONTAINERENTRY,
    '__module__' : 'record_pb2'
    # @@protoc_insertion_point(class_scope:codewithgpu.FeatureMap.ContainerEntry)
    })
  ,
  'DESCRIPTOR' : _FEATUREMAP,
  '__module__' : 'record_pb2'
  # @@protoc_insertion_point(class_scope:codewithgpu.FeatureMap)
  })
_sym_db.RegisterMessage(FeatureMap)
_sym_db.RegisterMessage(FeatureMap.ContainerEntry)


DESCRIPTOR._options = None
_FEATUREMAP_CONTAINERENTRY._options = None
# @@protoc_insertion_point(module_scope)
